---

- name: Update the hostname - hostname cmd
  hostname:
    name: "{{hostname_short}}"

- name: Update the hostname - (/etc/hostname)
  copy:
    content: "{{hostname_short}}\n"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644

- name: Update the hostname - (/etc/hosts)
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644

